-- No-op: rows deleted by the up migration cannot be recovered.
-- The corresponding up migration removed low-quality audit rows
-- (empty record_snapshot + boolean-only changed_fields) that were
-- generated by the pre-fix LEI link reconciliation pass.
SELECT 1 AS col1;
